[window]
dynamic_padding = true
decorations = "Full"

[font]
size = 12.0
normal =      { family = "FiraCode Nerd Font Mono", style = "Normal" }
bold =        { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic =      { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold italic" }

[colors]
draw_bold_text_with_bright_colors = true
[colors.primary]
foreground = "#D3D7CF"
background = "#1E2122"
